server:
  port: 8090

spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      show-sql: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/telran
    username: postgres
    password: 1234

logging:
  loggingXml: false
  file:
    name: hello-spring-boot.log
